import { v4 as uuidv4 } from 'https://jspm.dev/uuid'

export const voomsData = [   
    {
        handle: `@RealGraceDyke 💎`,
        profilePic: `/images/dykegrace.jpeg`,
        likes: 27,
        revooms: 10,
        voomText: `Buy Bitcoin, ETH Make 💰💰💰 low low prices. 
            Guaranteed return on investment. HMU DMs open!!`,
        replies: [
            {
                handle: `@QueenBofEngland ✅`,
                profilePic: `/images/queenB.jpeg`,
                voomText: `Yes! Sign me up! 😎🛩`,
                likes: 750,
                revooms: 18,
                replies: [
                    {
                    handle: `@sukala.Hull ✅`,
                    profilePic: `/images/queenB.jpeg`,
                    voomText: `Yes! Sign me up! 😎🛩`,
                    likes: 750,
                    revooms: 18,
                    replies: [],
                    isLiked: false,
                    isReVoomed: false,
                    uuid: 'cd76c4d0-1c09-4322-baa2-ccc55f782661',
                },
                ],
                isLiked: false,
                isReVoomed: false,
                uuid: 'cd76cad0-1c09-4322-baa2-ccc55f782661',
            },
        ],
        isLiked: false,
        isReVoomed: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
    },    
    {
        handle: `@Gabby ✅`,
        profilePic: `/images/gabby.jpeg`,
        likes: 6500,
        revooms: 234,
        voomText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
        replies: [
                  {
                handle: `@Loveth104 ✅`,
                profilePic: `/images/loveth.jpeg`,
                voomText: `Yes! Sign me up! 😎🛩`,
                likes: 750,
                revooms: 18,
                replies: [
                    {
                        handle: `@kkeasy`,
                        profilePic: `/images/queenB.jpeg`,
                        voomText: `Yes! Sign me up! 😎🛩`,
                        likes: 750,
                        revooms: 18,
                        replies: [],
                        isLiked: false,
                        isReVoomed: false,
                        uuid: 'cd76cad0-1c09-4jw2-baa2-ccc55f782661',
                    },
                ],
                isLiked: false,
                isReVoomed: false,
                uuid: 'd7ea1dad-d193-40d2-a94b-31c1791dcd45',
                
            },
                  {
                handle: `@Ozurumba404 ✅`,
                profilePic: `/images/bubenation.jpeg`,
                voomText: `I went last year😴`,
                likes: 107,
                revooms: 85,
                replies: [ 
                    {
                        handle: `@Syla2a`,
                        profilePic: `/images/queenB.jpeg`,
                        voomText: `Yes! Sign me up! 😎🛩`,
                        likes: 750,
                        revooms: 18,
                        replies: [],
                        isLiked: false,
                        isReVoomed: false,
                        uuid: 'cd76cad0-1c09-4322-baa2-cc585f782661',
                    },
                ],
                isLiked: false,
                isReVoomed: false,
                uuid: '471ec488-bc72-4e83-a8d0-48765c50ad60',
            },
        ],
        isLiked: false,
        isReVoomed: false,
        uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs2',
    },
    {
        handle: `@Darlington81a`,
        profilePic: `/images/darlington.jpeg`,
        likes: 10,
        revooms: 3,
        voomText: `Are you a coder if you only know HTML?`,
        replies: [
            {
                handle: `@Ifesinachi1994 ☣️`,
                profilePic: `/images/ifesinachi.jpeg`,
                voomText: `No. Obviosuly not. Go get a job in McDonald's.`,
                likes: 2,
                revooms: 10,
                replies: [
                    {
                        handle: `@eaxra ✅`,
                        profilePic: `/images/queenB.jpeg`,
                        voomText: `Yes! Sign me up! 😎🛩`,
                        likes: 750,
                        revooms: 18,
                        replies: [],
                        isLiked: false,
                        isReVoomed: false,
                        uuid: 'cdpocad0-1c09-4322-baa2-ccc55f782661',
                    },
                ],
                isLiked: false,
                isReVoomed: false,
                uuid: 'e2ad08d2-ac95-4bf7-8797-4016c7676d60',
            },
            {
                handle: `@ElonMusk`,
                profilePic: `/images/elon-icon.jpg`,
                voomText: `You are wonderful just as you are! ❤️`,
                likes: 7,
                revooms: 15,
                replies: [
                    {
                        handle: `@042Man ✅`,
                        profilePic: `/images/queenB.jpeg`,
                        voomText: `Yes! Sign me up! 😎🛩`,
                        likes: 750,
                        revooms: 18,
                        replies: [],
                        isLiked: false,
                        isReVoomed: false,
                        uuid: 'cd76cad0-1c09-4322-baa2-ccc55f782661',
                    },
                ],
                isLiked: false,
                isReVoomed: false,
                uuid: '4d98537e-05e5-428e-955e-7c69c12a2667',
            },
        ],
        isLiked: false,
        isReVoomed: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys45',
   },     
]